version: "3.9"
   
services:
  uploader-service:
    build: ./uploader/.
    ports:
      - "3000:3000"
    environment:
      - REGION=${S3_REGION}
      - ACCESS_KEY=${S3_ACCESS_KEY}
      - SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - DATABASE_URL=${DATABASE_URL}
    command: npm run dev

  # converter_service:
  #   build: ./converter_service/.
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./converter_service/.:/code
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_NAME=${DATABASE_NAME}
  #     - DATABASE_USER=${DATABASE_USER}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #     - DATABASE_HOST=${DATABASE_HOST}
